// Art Bible v1.2に基づく正式な高精細敵素材。
// 図鑑用キーアートと戦闘用の透過素材を分離する。
const ENEMY_ASSETS = {
  runeSlime: 'assets/enemies/unique/rune-slime-cutout-v1.png',
  runeCrystal: 'assets/enemies/unique/rune-crystal-cutout-v1.png',
  glitchSpider: 'assets/enemies/unique/glitch-spider-cutout-v1.png',
  runeGolem: 'assets/enemies/unique/rune-golem-cutout-v1.png',
  glitchMimic: 'assets/enemies/unique/glitch-mimic-cutout-v1.png',
  runeElemental: 'assets/enemies/unique/rune-elemental-cutout-v1.png',
  skeletonSoldier: 'assets/enemies/unique/skeleton-soldier-cutout-v1.png',
  machineDrone: 'assets/enemies/unique/machine-drone-cutout-v1.png',
  rustedSpearman: 'assets/enemies/unique/rusted-spearman-cutout-v1.png',
  glitchSpark: 'assets/enemies/unique/glitch-spark-cutout-v1.png',
  armoredTroll: 'assets/enemies/unique/armored-troll-cutout-v1.png',
  cyclops: 'assets/enemies/unique/cyclops-cutout-v1.png',
  stoneTroll: 'assets/enemies/unique/stone-troll-cutout-v1.png',
  glitchGolem: 'assets/enemies/unique/glitch-golem-cutout-v1.png',
  spikeBall: 'assets/enemies/unique/spike-ball-cutout-v1.png',
  darkMage: 'assets/enemies/unique/dark-mage-cutout-v1.png',
  runeHunter: 'assets/enemies/unique/rune-hunter-cutout-v1.png',
  deathKnight: 'assets/enemies/unique/death-knight-cutout-v1.png',
  runeGuardian: 'assets/enemies/unique/rune-guardian-cutout-v1.png',
  noiseFallen: 'assets/enemies/unique/noise-fallen-cutout-v1.png',
  glitchMaiden: 'assets/enemies/unique/glitch-maiden-cutout-v1.png',
  shadowBat: 'assets/enemies/unique/shadow-bat-cutout-v1.png',
  noiseImp: 'assets/enemies/unique/noise-imp-cutout-v1.png',
  voidScorpion: 'assets/enemies/unique/void-scorpion-cutout-v1.png',
  shadowWolf: 'assets/enemies/unique/shadow-wolf-cutout-v1.png',
  voidKnight: 'assets/enemies/unique/void-knight-cutout-v1.png',
  abyssSpirit: 'assets/enemies/unique/abyss-spirit-cutout-v1.png',
  darkSlime: 'assets/enemies/unique/dark-slime-cutout-v1.png',
  goblinWarrior: 'assets/enemies/unique/goblin-warrior-cutout-v1.png',
  goblinArcher: 'assets/enemies/unique/goblin-archer-cutout-v1.png',
  woodSlime: 'assets/enemies/unique/wood-slime-cutout-v1.png',
  blindBat: 'assets/enemies/unique/blind-bat-cutout-v1.png',
  darkWolf: 'assets/enemies/unique/dark-wolf-cutout-v1.png',
  shadowImp: 'assets/enemies/unique/shadow-imp-cutout-v1.png',
  shadowSlime: 'assets/enemies/unique/shadow-slime-cutout-v1.png',
  voidSlime: 'assets/enemies/unique/void-slime-cutout-v1.png',
  darkImp: 'assets/enemies/unique/dark-imp-cutout-v1.png',
  goblinShaman: 'assets/enemies/unique/goblin-shaman-cutout-v2.png',
  windImp: 'assets/enemies/unique/wind-imp-cutout-v2.png',
  earthImp: 'assets/enemies/unique/earth-imp-cutout-v2.png',
  lightImp: 'assets/enemies/unique/light-imp-cutout-v1.png',
  ghost: 'assets/enemies/unique/ghost-cutout-v1.png',
  lightSlime: 'assets/enemies/unique/light-slime-cutout-v2.png',
  poisonSlime: 'assets/enemies/unique/poison-slime-cutout-v1.png',
  indexBlade: 'assets/enemies/unique/index-blade-cutout-v1.png',
  corruptGuardian: 'assets/enemies/unique/corrupt-guardian-cutout-v1.png',
  sandWorm: 'assets/enemies/unique/sand-worm-cutout-v1.png',
  cursePriest: 'assets/enemies/unique/curse-priest-cutout-v1.png',
  shadowChimera: 'assets/enemies/unique/shadow-chimera-cutout-v1.png',
  voidReaper: 'assets/enemies/unique/void-reaper-cutout-v1.png',
  bloodGolem: 'assets/enemies/unique/blood-golem-cutout-v1.png',
  youngDarkDragon: 'assets/enemies/unique/young-dark-dragon-cutout-v1.png',
  shadowAssassin: 'assets/enemies/unique/shadow-assassin-cutout-v1.png',
  cursedSwordsman: 'assets/enemies/unique/cursed-swordsman-cutout-v1.png',
  cursedKnight: 'assets/enemies/unique/cursed-knight-cutout-v1.png',
  crystalWorm: 'assets/enemies/unique/crystal-worm-cutout-v1.png',
  voidHound: 'assets/enemies/unique/void-hound-cutout-v1.png',
  hellStalker: 'assets/enemies/unique/hell-stalker-cutout-v1.png',
  voidDrake: 'assets/enemies/unique/void-drake-cutout-v1.png',
  darkFairy: 'assets/enemies/unique/dark-fairy-cutout-v1.png',
  skeletonArcher: 'assets/enemies/unique/skeleton-archer-cutout-v1.png',
  goblinBombardier: 'assets/enemies/unique/goblin-bombardier-cutout-v1.png',
  bloodLeech: 'assets/enemies/unique/blood-leech-cutout-v1.png',
  cultist: 'assets/enemies/unique/cultist-cutout-v1.png',
  berserker: 'assets/enemies/unique/berserker-cutout-v1.png',
  sisterWorm: 'assets/enemies/unique/sister-worm-cutout-v1.png',
  runeMage: 'assets/enemies/unique/rune-mage-cutout-v1.png',
  noiseSlime: 'assets/enemies/unique/noise-slime-cutout-v1.png',
  crystalWormVariation: 'assets/enemies/unique/crystal-worm-variation-cutout-v1.png',
  crystalWorm: 'assets/enemies/unique/crystal-worm-cutout-v1.png',
  voidHound: 'assets/enemies/unique/void-hound-cutout-v1.png',
  hellStalker: 'assets/enemies/unique/hell-stalker-cutout-v1.png',
  voidDrake: 'assets/enemies/unique/void-drake-cutout-v1.png',
  darkFairy: 'assets/enemies/unique/dark-fairy-cutout-v1.png',
  skeletonArcher: 'assets/enemies/unique/skeleton-archer-cutout-v1.png',
  goblinBombardier: 'assets/enemies/unique/goblin-bombardier-cutout-v1.png',
  bloodLeech: 'assets/enemies/unique/blood-leech-cutout-v1.png',
  cultist: 'assets/enemies/unique/cultist-cutout-v1.png',
  berserker: 'assets/enemies/unique/berserker-cutout-v1.png',
  sisterWorm: 'assets/enemies/unique/sister-worm-cutout-v1.png',
  runeMage: 'assets/enemies/unique/rune-mage-cutout-v1.png',
  noiseSlime: 'assets/enemies/unique/noise-slime-cutout-v1.png',
  crystalWormVariation: 'assets/enemies/unique/crystal-worm-variation-cutout-v1.png',
  glitch: 'assets/enemies/glitch-v2.png',
  ember: 'assets/enemies/ember-v2.png',
  wisp: 'assets/enemies/wisp-v2.png',
  shell: 'assets/enemies/shell-v2.png',
  twins: 'assets/enemies/twins-v2.png',
  noise: 'assets/enemies/noise-v2.png',
  wordeater: 'assets/enemies/wordeater-v2.png',
  pyre: 'assets/enemies/pyre-v2.png',
  mirror: 'assets/enemies/mirror-v2.png',
  leech: 'assets/enemies/leech-v2.png',
  guardian: 'assets/enemies/guardian-v2.png',
  guardian1: 'assets/enemies/guardian-v2.png',
  guardian2: 'assets/enemies/guardian-v2.png',
  guardian3: 'assets/enemies/guardian-v2.png',
  guardian4: 'assets/enemies/guardian-v2.png',
  guardian5: 'assets/enemies/guardian-v2.png',
  sovereign: 'assets/enemies/sovereign-v2.png',
  noxshade: 'assets/enemies/mirror-v2.png',
  senrinseal: 'assets/enemies/guardian-v2.png',
  nullking: 'assets/enemies/sovereign-v2.png',
  bossGaius: 'assets/enemies/boss-gaius-cutout-v1.png',
  bossVolcarion: 'assets/enemies/boss-volcarion-cutout-v1.png',
  bossCelestia: 'assets/enemies/boss-celestia-cutout-v1.png',
  bossAgniros: 'assets/enemies/boss-agniros-cutout-v1.png',
  bossFrostnova: 'assets/enemies/boss-frostnova-cutout-v1.png',
  bossRaidingald: 'assets/enemies/boss-raidingald-cutout-v1.png',
  kingChronos: 'assets/enemies/king-chronos-cutout-v1.png',
  kingAerpocalion: 'assets/enemies/king-aerpocalion-cutout-v1.png',
  kingNecros: 'assets/enemies/king-necros-cutout-v1.png',
  alphaOrigin: 'assets/enemies/alpha-origin-cutout-v1.png',
  troll: 'assets/enemies/unique/troll-cutout-v1.png',
  bloodOgre: 'assets/enemies/unique/blood-ogre-cutout-v1.png',
  flameSlime: 'assets/enemies/unique/flame-slime-cutout-v1.png',
  iceSlime: 'assets/enemies/unique/ice-slime-cutout-v1.png',
  stormSlime: 'assets/enemies/unique/storm-slime-cutout-v1.png',
  earthSlime: 'assets/enemies/unique/earth-slime-cutout-v1.png',
  skeletonMage: 'assets/enemies/unique/skeleton-mage-cutout-v1.png',
  fireImp: 'assets/enemies/unique/fire-imp-cutout-v1.png',
  iceImp: 'assets/enemies/unique/ice-imp-cutout-v1.png',
  thunderImp: 'assets/enemies/unique/thunder-imp-cutout-v1.png',
  plasmaSlime: 'assets/enemies/unique/plasma-slime-cutout-v1.png',
};

// 戦闘では背景の焼き込みがない専用素材を優先する。
// 図鑑では従来の背景付きイラストを維持し、用途ごとの見栄えを両立する。
const BATTLE_ENEMY_ASSETS = {
  runeSlime: 'assets/enemies/unique/rune-slime-cutout-v1.png',
  runeCrystal: 'assets/enemies/unique/rune-crystal-cutout-v1.png',
  glitchSpider: 'assets/enemies/unique/glitch-spider-cutout-v1.png',
  runeGolem: 'assets/enemies/unique/rune-golem-cutout-v1.png',
  glitchMimic: 'assets/enemies/unique/glitch-mimic-cutout-v1.png',
  runeElemental: 'assets/enemies/unique/rune-elemental-cutout-v1.png',
  skeletonSoldier: 'assets/enemies/unique/skeleton-soldier-cutout-v1.png',
  machineDrone: 'assets/enemies/unique/machine-drone-cutout-v1.png',
  rustedSpearman: 'assets/enemies/unique/rusted-spearman-cutout-v1.png',
  glitchSpark: 'assets/enemies/unique/glitch-spark-cutout-v1.png',
  armoredTroll: 'assets/enemies/unique/armored-troll-cutout-v1.png',
  cyclops: 'assets/enemies/unique/cyclops-cutout-v1.png',
  stoneTroll: 'assets/enemies/unique/stone-troll-cutout-v1.png',
  glitchGolem: 'assets/enemies/unique/glitch-golem-cutout-v1.png',
  spikeBall: 'assets/enemies/unique/spike-ball-cutout-v1.png',
  darkMage: 'assets/enemies/unique/dark-mage-cutout-v1.png',
  runeHunter: 'assets/enemies/unique/rune-hunter-cutout-v1.png',
  deathKnight: 'assets/enemies/unique/death-knight-cutout-v1.png',
  runeGuardian: 'assets/enemies/unique/rune-guardian-cutout-v1.png',
  noiseFallen: 'assets/enemies/unique/noise-fallen-cutout-v1.png',
  glitchMaiden: 'assets/enemies/unique/glitch-maiden-cutout-v1.png',
  shadowBat: 'assets/enemies/unique/shadow-bat-cutout-v1.png',
  noiseImp: 'assets/enemies/unique/noise-imp-cutout-v1.png',
  voidScorpion: 'assets/enemies/unique/void-scorpion-cutout-v1.png',
  shadowWolf: 'assets/enemies/unique/shadow-wolf-cutout-v1.png',
  voidKnight: 'assets/enemies/unique/void-knight-cutout-v1.png',
  abyssSpirit: 'assets/enemies/unique/abyss-spirit-cutout-v1.png',
  darkSlime: 'assets/enemies/unique/dark-slime-cutout-v1.png',
  goblinWarrior: 'assets/enemies/unique/goblin-warrior-cutout-v1.png',
  goblinArcher: 'assets/enemies/unique/goblin-archer-cutout-v1.png',
  woodSlime: 'assets/enemies/unique/wood-slime-cutout-v1.png',
  blindBat: 'assets/enemies/unique/blind-bat-cutout-v1.png',
  darkWolf: 'assets/enemies/unique/dark-wolf-cutout-v1.png',
  shadowImp: 'assets/enemies/unique/shadow-imp-cutout-v1.png',
  shadowSlime: 'assets/enemies/unique/shadow-slime-cutout-v1.png',
  voidSlime: 'assets/enemies/unique/void-slime-cutout-v1.png',
  darkImp: 'assets/enemies/unique/dark-imp-cutout-v1.png',
  goblinShaman: 'assets/enemies/unique/goblin-shaman-cutout-v2.png',
  windImp: 'assets/enemies/unique/wind-imp-cutout-v2.png',
  earthImp: 'assets/enemies/unique/earth-imp-cutout-v2.png',
  lightImp: 'assets/enemies/unique/light-imp-cutout-v1.png',
  ghost: 'assets/enemies/unique/ghost-cutout-v1.png',
  lightSlime: 'assets/enemies/unique/light-slime-cutout-v2.png',
  poisonSlime: 'assets/enemies/unique/poison-slime-cutout-v1.png',
  indexBlade: 'assets/enemies/unique/index-blade-cutout-v1.png',
  corruptGuardian: 'assets/enemies/unique/corrupt-guardian-cutout-v1.png',
  sandWorm: 'assets/enemies/unique/sand-worm-cutout-v1.png',
  cursePriest: 'assets/enemies/unique/curse-priest-cutout-v1.png',
  shadowChimera: 'assets/enemies/unique/shadow-chimera-cutout-v1.png',
  voidReaper: 'assets/enemies/unique/void-reaper-cutout-v1.png',
  bloodGolem: 'assets/enemies/unique/blood-golem-cutout-v1.png',
  youngDarkDragon: 'assets/enemies/unique/young-dark-dragon-cutout-v1.png',
  shadowAssassin: 'assets/enemies/unique/shadow-assassin-cutout-v1.png',
  cursedSwordsman: 'assets/enemies/unique/cursed-swordsman-cutout-v1.png',
  cursedKnight: 'assets/enemies/unique/cursed-knight-cutout-v1.png',
  crystalWorm: 'assets/enemies/unique/crystal-worm-cutout-v1.png',
  voidHound: 'assets/enemies/unique/void-hound-cutout-v1.png',
  hellStalker: 'assets/enemies/unique/hell-stalker-cutout-v1.png',
  voidDrake: 'assets/enemies/unique/void-drake-cutout-v1.png',
  darkFairy: 'assets/enemies/unique/dark-fairy-cutout-v1.png',
  skeletonArcher: 'assets/enemies/unique/skeleton-archer-cutout-v1.png',
  goblinBombardier: 'assets/enemies/unique/goblin-bombardier-cutout-v1.png',
  bloodLeech: 'assets/enemies/unique/blood-leech-cutout-v1.png',
  cultist: 'assets/enemies/unique/cultist-cutout-v1.png',
  berserker: 'assets/enemies/unique/berserker-cutout-v1.png',
  sisterWorm: 'assets/enemies/unique/sister-worm-cutout-v1.png',
  runeMage: 'assets/enemies/unique/rune-mage-cutout-v1.png',
  noiseSlime: 'assets/enemies/unique/noise-slime-cutout-v1.png',
  crystalWormVariation: 'assets/enemies/unique/crystal-worm-variation-cutout-v1.png',
  glitch: 'assets/enemies/glitch-cutout-v3.png',
  ember: 'assets/enemies/glitch-cutout-v3.png',
  wisp: 'assets/enemies/glitch-cutout-v3.png',
  shell: 'assets/enemies/shell-cutout-v3.png',
  twins: 'assets/enemies/wordeater-cutout-v3.png',
  noise: 'assets/enemies/glitch-cutout-v3.png',
  wordeater: 'assets/enemies/wordeater-cutout-v3.png',
  pyre: 'assets/enemies/wordeater-cutout-v3.png',
  mirror: 'assets/enemies/guardian-cutout-v3.png',
  leech: 'assets/enemies/wordeater-cutout-v3.png',
  guardian: 'assets/enemies/guardian-cutout-v3.png',
  guardian1: 'assets/enemies/guardian-cutout-v3.png',
  guardian2: 'assets/enemies/guardian-cutout-v3.png',
  guardian3: 'assets/enemies/guardian-cutout-v3.png',
  guardian4: 'assets/enemies/guardian-cutout-v3.png',
  guardian5: 'assets/enemies/guardian-cutout-v3.png',
  sovereign: 'assets/enemies/sovereign-cutout-v4.png',
  noxshade: 'assets/enemies/noxshade-cutout-v4.png',
  senrinseal: 'assets/enemies/senrinseal-cutout-v4.png',
  nullking: 'assets/enemies/nullking-cutout-v4.png',
  bossGaius: 'assets/enemies/boss-gaius-cutout-v1.png',
  bossVolcarion: 'assets/enemies/boss-volcarion-cutout-v1.png',
  bossCelestia: 'assets/enemies/boss-celestia-cutout-v1.png',
  bossAgniros: 'assets/enemies/boss-agniros-cutout-v1.png',
  bossFrostnova: 'assets/enemies/boss-frostnova-cutout-v1.png',
  bossRaidingald: 'assets/enemies/boss-raidingald-cutout-v1.png',
  kingChronos: 'assets/enemies/king-chronos-cutout-v1.png',
  kingAerpocalion: 'assets/enemies/king-aerpocalion-cutout-v1.png',
  kingNecros: 'assets/enemies/king-necros-cutout-v1.png',
  alphaOrigin: 'assets/enemies/alpha-origin-cutout-v1.png',
  troll: 'assets/enemies/unique/troll-cutout-v1.png',
  bloodOgre: 'assets/enemies/unique/blood-ogre-cutout-v1.png',
  flameSlime: 'assets/enemies/unique/flame-slime-cutout-v1.png',
  iceSlime: 'assets/enemies/unique/ice-slime-cutout-v1.png',
  stormSlime: 'assets/enemies/unique/storm-slime-cutout-v1.png',
  earthSlime: 'assets/enemies/unique/earth-slime-cutout-v1.png',
  skeletonMage: 'assets/enemies/unique/skeleton-mage-cutout-v1.png',
  fireImp: 'assets/enemies/unique/fire-imp-cutout-v1.png',
  iceImp: 'assets/enemies/unique/ice-imp-cutout-v1.png',
  thunderImp: 'assets/enemies/unique/thunder-imp-cutout-v1.png',
  plasmaSlime: 'assets/enemies/unique/plasma-slime-cutout-v1.png',
};

// 敵ごとにシルエットと安全余白が異なるため、一律の拡大率を使用しない。
// 数値は戦闘キャンバス内での表示倍率・位置・接地点を表す。
const DEFAULT_BATTLE_LAYOUT = {
  scale: .78,
  x: '0%',
  y: '3%',
  ground: '92%',
  shadowWidth: '70%',
  shadowOpacity: .7,
  float: '4px',
  origin: 'center bottom',
  grade: .94,
};

const BATTLE_ENEMY_LAYOUTS = {
  runeSlime: { scale: .47, y: '1%', shadowWidth: '42%', float: '3px', grade: .9 },
  runeCrystal: { scale: .5, y: '0%', ground: '66%', shadowWidth: '42%', shadowOpacity: .42, float: '5px', origin: 'center center', grade: .9 },
  glitchSpider: { scale: .49, y: '1%', shadowWidth: '52%', float: '2px', grade: .88 },
  runeGolem: { scale: .57, y: '1%', shadowWidth: '48%', float: '2px', grade: .86 },
  glitchMimic: { scale: .67, y: '0%', shadowWidth: '62%', float: '2px', grade: .88 },
  runeElemental: { scale: .76, y: '0%', ground: '64%', shadowWidth: '58%', shadowOpacity: .44, float: '4px', origin: 'center center', grade: .9 },
  skeletonSoldier: { scale: .53, y: '1%', shadowWidth: '42%', float: '2px', grade: .88 },
  machineDrone: { scale: .46, y: '0%', ground: '65%', shadowWidth: '40%', shadowOpacity: .4, float: '5px', origin: 'center center', grade: .9 },
  rustedSpearman: { scale: .53, y: '1%', shadowWidth: '42%', float: '2px', grade: .86 },
  glitchSpark: { scale: .43, y: '0%', ground: '65%', shadowWidth: '36%', shadowOpacity: .38, float: '6px', origin: 'center center', grade: .92 },
  armoredTroll: { scale: .67, y: '1%', shadowWidth: '64%', float: '2px', grade: .86 },
  cyclops: { scale: .76, y: '0%', shadowWidth: '68%', float: '2px', grade: .87 },
  stoneTroll: { scale: .55, y: '1%', shadowWidth: '50%', float: '2px', grade: .86 },
  glitchGolem: { scale: .55, y: '1%', shadowWidth: '48%', float: '2px', grade: .88 },
  spikeBall: { scale: .43, y: '0%', ground: '65%', shadowWidth: '34%', shadowOpacity: .36, float: '6px', origin: 'center center', grade: .9 },
  darkMage: { scale: .67, y: '0%', ground: '65%', shadowWidth: '48%', shadowOpacity: .42, float: '4px', origin: 'center center', grade: .88 },
  runeHunter: { scale: .66, y: '1%', shadowWidth: '46%', float: '3px', grade: .88 },
  deathKnight: { scale: .77, y: '0%', shadowWidth: '60%', float: '2px', grade: .86 },
  runeGuardian: { scale: .64, x: '-1%', y: '1%', shadowWidth: '58%', float: '2px', grade: .86 },
  noiseFallen: { scale: .62, x: '-1%', y: '0%', ground: '65%', shadowWidth: '48%', shadowOpacity: .4, float: '4px', origin: 'center center', grade: .88 },
  glitchMaiden: { scale: .72, y: '0%', ground: '64%', shadowWidth: '58%', shadowOpacity: .42, float: '4px', origin: 'center center', grade: .88 },
  shadowBat: { scale: .45, y: '0%', ground: '65%', shadowWidth: '38%', shadowOpacity: .34, float: '7px', origin: 'center center', grade: .88 },
  noiseImp: { scale: .44, y: '0%', ground: '65%', shadowWidth: '34%', shadowOpacity: .34, float: '6px', origin: 'center center', grade: .9 },
  voidScorpion: { scale: .49, y: '1%', shadowWidth: '54%', float: '2px', grade: .86 },
  shadowWolf: { scale: .5, x: '-1%', y: '1%', shadowWidth: '54%', float: '2px', grade: .86 },
  voidKnight: { scale: .69, y: '1%', shadowWidth: '62%', float: '2px', grade: .86 },
  abyssSpirit: { scale: .76, y: '0%', ground: '63%', shadowWidth: '60%', shadowOpacity: .4, float: '5px', origin: 'center center', grade: .88 },
  darkSlime: { scale: .44, y: '0%', ground: '65%', shadowWidth: '36%', shadowOpacity: .34, float: '5px', origin: 'center center', grade: .9 },
  goblinWarrior: { scale: .53, y: '1%', shadowWidth: '44%', float: '2px', grade: .87 },
  goblinArcher: { scale: .51, y: '1%', shadowWidth: '42%', float: '2px', grade: .87 },
  woodSlime: { scale: .45, y: '0%', ground: '65%', shadowWidth: '38%', shadowOpacity: .34, float: '4px', origin: 'center center', grade: .9 },
  blindBat: { scale: .44, y: '0%', ground: '65%', shadowWidth: '36%', shadowOpacity: .34, float: '7px', origin: 'center center', grade: .88 },
  darkWolf: { scale: .50, x: '-1%', y: '1%', shadowWidth: '54%', float: '2px', grade: .86 },
  shadowImp: { scale: .42, y: '0%', ground: '65%', shadowWidth: '38%', shadowOpacity: .34, float: '6px', origin: 'center center', grade: .88 },
  shadowSlime: { scale: .44, y: '0%', ground: '65%', shadowWidth: '40%', shadowOpacity: .34, float: '5px', origin: 'center center', grade: .9 },
  voidSlime: { scale: .46, y: '0%', ground: '65%', shadowWidth: '42%', shadowOpacity: .36, float: '6px', origin: 'center center', grade: .9 },
  darkImp: { scale: .46, y: '0%', ground: '64%', shadowWidth: '44%', shadowOpacity: .36, float: '5px', origin: 'center center', grade: .88 },
  goblinShaman: { scale: .53, y: '1%', shadowWidth: '46%', float: '2px', grade: .86 },
  windImp: { scale: .44, y: '0%', ground: '65%', shadowWidth: '38%', shadowOpacity: .34, float: '7px', origin: 'center center', grade: .9 },
  earthImp: { scale: .5, y: '1%', shadowWidth: '48%', float: '2px', grade: .86 },
  lightImp: { scale: .47, y: '0%', ground: '64%', shadowWidth: '42%', shadowOpacity: .34, float: '6px', origin: 'center center', grade: .92 },
  ghost: { scale: .55, y: '0%', ground: '64%', shadowWidth: '42%', shadowOpacity: .3, float: '6px', origin: 'center center', grade: .88 },
  lightSlime: { scale: .44, y: '0%', ground: '65%', shadowWidth: '40%', shadowOpacity: .34, float: '4px', origin: 'center center', grade: .94 },
  poisonSlime: { scale: .45, y: '0%', ground: '65%', shadowWidth: '42%', shadowOpacity: .36, float: '4px', origin: 'center center', grade: .88 },
  indexBlade: { scale: .66, y: '0%', ground: '64%', shadowWidth: '58%', shadowOpacity: .42, float: '3px', origin: 'center center', grade: .86 },
  corruptGuardian: { scale: .62, y: '1%', shadowWidth: '66%', float: '2px', grade: .84 },
  sandWorm: { scale: .58, y: '1%', ground: '65%', shadowWidth: '68%', shadowOpacity: .48, float: '2px', origin: 'center center', grade: .86 },
  cursePriest: { scale: .68, y: '0%', ground: '63%', shadowWidth: '56%', shadowOpacity: .38, float: '5px', origin: 'center center', grade: .88 },
  shadowChimera: { scale: .65, y: '0%', ground: '65%', shadowWidth: '70%', shadowOpacity: .44, float: '2px', origin: 'center center', grade: .86 },
  voidReaper: { scale: .68, y: '0%', ground: '63%', shadowWidth: '58%', shadowOpacity: .4, float: '3px', origin: 'center center', grade: .88 },
  bloodGolem: { scale: .72, y: '0%', shadowWidth: '72%', float: '2px', grade: .84 },
  youngDarkDragon: { scale: .68, y: '1%', ground: '66%', shadowWidth: '72%', shadowOpacity: .44, float: '2px', origin: 'center center', grade: .86 },
  shadowAssassin: { scale: .62, y: '0%', ground: '65%', shadowWidth: '64%', shadowOpacity: .4, float: '3px', origin: 'center center', grade: .87 },
  cursedSwordsman: { scale: .72, y: '0%', shadowWidth: '62%', float: '2px', grade: .86 },
  cursedKnight: { scale: .7, y: '0%', shadowWidth: '70%', float: '2px', grade: .86 },
  crystalWorm: { scale: .58, y: '1%', ground: '66%', shadowWidth: '68%', shadowOpacity: .42, float: '2px', origin: 'center center', grade: .9 },
  voidHound: { scale: .54, y: '1%', shadowWidth: '60%', float: '2px', grade: .87 },
  hellStalker: { scale: .62, y: '1%', shadowWidth: '62%', float: '2px', grade: .86 },
  voidDrake: { scale: .6, y: '0%', ground: '65%', shadowWidth: '66%', shadowOpacity: .4, float: '3px', origin: 'center center', grade: .87 },
  darkFairy: { scale: .44, y: '0%', ground: '64%', shadowWidth: '40%', shadowOpacity: .3, float: '7px', origin: 'center center', grade: .9 },
  skeletonArcher: { scale: .5, y: '1%', shadowWidth: '42%', float: '2px', grade: .88 },
  goblinBombardier: { scale: .47, y: '1%', shadowWidth: '44%', float: '2px', grade: .88 },
  bloodLeech: { scale: .42, y: '0%', ground: '65%', shadowWidth: '36%', shadowOpacity: .34, float: '6px', origin: 'center center', grade: .9 },
  cultist: { scale: .6, y: '0%', ground: '64%', shadowWidth: '48%', shadowOpacity: .4, float: '4px', origin: 'center center', grade: .88 },
  berserker: { scale: .64, y: '1%', shadowWidth: '62%', float: '2px', grade: .86 },
  sisterWorm: { scale: .6, y: '0%', ground: '65%', shadowWidth: '64%', shadowOpacity: .4, float: '3px', origin: 'center center', grade: .88 },
  runeMage: { scale: .55, y: '0%', ground: '64%', shadowWidth: '42%', shadowOpacity: .34, float: '6px', origin: 'center center', grade: .9 },
  noiseSlime: { scale: .44, y: '0%', ground: '65%', shadowWidth: '38%', shadowOpacity: .34, float: '5px', origin: 'center center', grade: .9 },
  crystalWormVariation: { scale: .5, y: '1%', ground: '66%', shadowWidth: '58%', shadowOpacity: .4, float: '2px', origin: 'center center', grade: .9 },
  troll: { scale: .64, y: '1%', shadowWidth: '62%', float: '2px', grade: .86 },
  bloodOgre: { scale: .7, y: '1%', shadowWidth: '68%', float: '2px', grade: .84 },
  flameSlime: { scale: .44, y: '0%', ground: '65%', shadowWidth: '40%', shadowOpacity: .34, float: '4px', origin: 'center center', grade: .9 },
  iceSlime: { scale: .44, y: '0%', ground: '65%', shadowWidth: '40%', shadowOpacity: .32, float: '4px', origin: 'center center', grade: .92 },
  stormSlime: { scale: .44, y: '0%', ground: '65%', shadowWidth: '40%', shadowOpacity: .34, float: '5px', origin: 'center center', grade: .9 },
  earthSlime: { scale: .45, y: '0%', ground: '65%', shadowWidth: '42%', shadowOpacity: .36, float: '3px', origin: 'center center', grade: .88 },
  skeletonMage: { scale: .55, y: '0%', ground: '64%', shadowWidth: '44%', shadowOpacity: .34, float: '5px', origin: 'center center', grade: .88 },
  fireImp: { scale: .44, y: '0%', ground: '65%', shadowWidth: '38%', shadowOpacity: .34, float: '7px', origin: 'center center', grade: .9 },
  iceImp: { scale: .44, y: '0%', ground: '65%', shadowWidth: '38%', shadowOpacity: .32, float: '7px', origin: 'center center', grade: .92 },
  thunderImp: { scale: .44, y: '0%', ground: '65%', shadowWidth: '38%', shadowOpacity: .34, float: '7px', origin: 'center center', grade: .9 },
  plasmaSlime: { scale: .45, y: '0%', ground: '65%', shadowWidth: '42%', shadowOpacity: .34, float: '5px', origin: 'center center', grade: .9 },
  glitch: { scale: .53, y: '2%', shadowWidth: '42%', float: '3px' },
  ember: { scale: .55, y: '2%', shadowWidth: '44%', float: '3px' },
  wisp: { scale: .52, y: '1%', shadowWidth: '40%', float: '5px' },
  shell: { scale: .58, y: '1%', shadowWidth: '50%', float: '2px' },
  twins: { scale: .63, y: '1%', shadowWidth: '54%', float: '4px' },
  noise: { scale: .59, y: '2%', shadowWidth: '48%', float: '4px' },
  wordeater: { scale: .75, y: '1%', shadowWidth: '62%' },
  pyre: { scale: .72, y: '1%', shadowWidth: '60%' },
  mirror: { scale: .73, y: '1%', shadowWidth: '58%' },
  leech: { scale: .72, y: '1%', shadowWidth: '58%' },
  guardian1: { scale: .92, y: '0%', shadowWidth: '72%' },
  guardian2: { scale: .92, y: '0%', shadowWidth: '72%' },
  guardian3: { scale: .92, y: '0%', shadowWidth: '72%' },
  guardian4: { scale: .92, y: '0%', shadowWidth: '72%' },
  guardian5: { scale: .92, y: '0%', shadowWidth: '72%' },
  noxshade: { scale: .90, x: '1%', y: '0%', shadowWidth: '58%', float: '2px' },
  senrinseal: { scale: .91, y: '0%', ground: '62%', shadowWidth: '58%', shadowOpacity: .42, float: '4px', origin: 'center center' },
  sovereign: { scale: .96, y: '0%', ground: '64%', shadowWidth: '66%', shadowOpacity: .46, float: '3px', origin: 'center center' },
  nullking: { scale: 1.00, x: '-1%', y: '0%', ground: '64%', shadowWidth: '70%', shadowOpacity: .5, float: '2px', origin: 'center center', grade: 1.02 },
  bossGaius: { scale: .88, x: '0%', y: '1%', ground: '65%', shadowWidth: '70%', shadowOpacity: .52, float: '2px', origin: 'center center', grade: .92 },
  bossVolcarion: { scale: .78, x: '-1%', y: '1%', ground: '64%', shadowWidth: '78%', shadowOpacity: .5, float: '3px', origin: 'center center', grade: .9 },
  bossCelestia: { scale: .85, x: '0%', y: '1%', ground: '64%', shadowWidth: '70%', shadowOpacity: .48, float: '4px', origin: 'center center', grade: .88 },
  bossAgniros: { scale: .86, x: '0%', y: '1%', ground: '65%', shadowWidth: '72%', shadowOpacity: .56, float: '2px', origin: 'center center', grade: .9 },
  bossFrostnova: { scale: .88, x: '0%', y: '1%', ground: '64%', shadowWidth: '68%', shadowOpacity: .5, float: '3px', origin: 'center center', grade: .88 },
  bossRaidingald: { scale: .84, x: '0%', y: '0%', ground: '63%', shadowWidth: '72%', shadowOpacity: .46, float: '4px', origin: 'center center', grade: .9 },
  kingChronos: { scale: .88, x: '0%', y: '0%', ground: '63%', shadowWidth: '70%', shadowOpacity: .48, float: '3px', origin: 'center center', grade: .94 },
  kingAerpocalion: { scale: .84, x: '-1%', y: '0%', ground: '64%', shadowWidth: '76%', shadowOpacity: .58, float: '2px', origin: 'center center', grade: .9 },
  kingNecros: { scale: .86, x: '0%', y: '0%', ground: '63%', shadowWidth: '70%', shadowOpacity: .5, float: '3px', origin: 'center center', grade: .9 },
  alphaOrigin: { scale: .82, x: '0%', y: '0%', ground: '62%', shadowWidth: '82%', shadowOpacity: .34, float: '5px', origin: 'center center', grade: .98 },
};

const GUARDIAN_MARKS = {
  guardian1: 'I',
  guardian2: 'II',
  guardian3: 'III',
  guardian4: 'IV',
  guardian5: 'V',
  sovereign: 'Ω',
  noxshade: 'N',
  senrinseal: '仙',
  nullking: '0',
};

export function enemyBattleStyle(id, enemy = null) {
  const tierScale = enemy?.tier === 'mob' ? .58 : enemy?.tier === 'elite' ? .7 : enemy?.tier === 'mid' ? .79 : .9;
  const layout = { ...DEFAULT_BATTLE_LAYOUT, scale: tierScale, ...(BATTLE_ENEMY_LAYOUTS[id] || {}) };
  return `--enemy-scale:${layout.scale};--enemy-x:${layout.x};--enemy-y:${layout.y};--enemy-ground:${layout.ground};--enemy-shadow-width:${layout.shadowWidth};--enemy-shadow-opacity:${layout.shadowOpacity};--enemy-float:${layout.float};--enemy-origin:${layout.origin};--enemy-grade:${layout.grade}`;
}

// 実装仕様書 v5.0 の標準データ契約。既存の短縮キーを残したまま、
// 図鑑・戦闘・将来の外部ツールから同じアート情報を参照できるようにする。
export function enemyAssetRecord(id, enemy = {}) {
  const artKey = enemy.artKey || id;
  const codex = ENEMY_ASSETS[id] || ENEMY_ASSETS[artKey] || ENEMY_ASSETS.glitch;
  const battle = BATTLE_ENEMY_ASSETS[id] || BATTLE_ENEMY_ASSETS[artKey] || codex;
  return { battle, codex, portrait: codex };
}

export function enemyPresentationRecord(id, enemy = {}) {
  const tierScale = enemy?.tier === 'mob' ? .58 : enemy?.tier === 'elite' ? .7 : enemy?.tier === 'mid' ? .79 : .9;
  const layout = { ...DEFAULT_BATTLE_LAYOUT, scale: tierScale, ...(BATTLE_ENEMY_LAYOUTS[id] || {}) };
  return { ...layout, lightingProfile: `stage-${enemy.stageId || 'shared'}` };
}

export function enemyArt(id, enemy, { locked = false, battle = false } = {}) {
  const artKey = enemy.artKey || id;
  const exactArt = ENEMY_ASSETS[id];
  const battleArt = BATTLE_ENEMY_ASSETS[id] || BATTLE_ENEMY_ASSETS[artKey];
  const hasBattleCutout = battle && Boolean(battleArt);
  const src = hasBattleCutout ? battleArt : (exactArt || ENEMY_ASSETS[artKey] || ENEMY_ASSETS.glitch);
  const label = locked ? '未発見の敵シルエット' : enemy.name;
  const artMark = enemy.artMark || GUARDIAN_MARKS[id] || '';
  const mark = artMark ? `<span class="enemy-art-mark" aria-hidden="true">${artMark}</span>` : '';
  const loading = battle ? 'eager' : 'lazy';
  const battleStyle = battle ? `;${enemyBattleStyle(id, enemy)}` : '';
  const hue = exactArt ? 0 : (enemy.artHue || 0);
  return `<figure class="enemy-art enemy-art-${id} ${enemy.tier} ${locked ? 'locked' : ''} ${battle ? 'battle-render' : ''} ${hasBattleCutout ? 'battle-cutout' : ''}" data-enemy-id="${id}" data-element="${enemy.element}" role="img" aria-label="${label}" style="--art-color:${enemy.color};--enemy-hue:${hue}deg${battleStyle}"><img class="enemy-art-image" src="${src}" alt="" loading="${loading}" decoding="async">${mark}<i class="enemy-art-element" aria-hidden="true"></i></figure>`;
}
